image: Visual Studio 2019

install:
  - gitversion /l console /output buildserver
  - dotnet tool install -g codecov.tool

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
  - dotnet build
  - dotnet pack

test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=./Coverage.xml

artifacts:
  - path: '**\*.nupkg'

after_test:
  - codecov -f test\ReportPortal.NUnitExtension.Tests\Coverage.xml